
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[156] =
    {   0,
        0,    0,   61,   59,   40,   39,   38,   59,   38,   44,
       59,   34,   35,   43,   41,   37,   42,   58,   45,   55,
       36,   48,   46,   47,   31,   32,   33,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       56,   59,   57,   50,    0,   27,    0,   54,   55,   52,
       49,   51,   31,    0,   31,   31,   31,   31,   31,   19,
       31,   31,   31,   31,   23,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   53,    0,   31,   31,
       31,   31,   31,   31,    9,   31,   31,   31,   28,   31,
       10,   31,   31,   31,   31,   29,   31,   31,   31,   31,

       30,   31,   31,   31,    1,   15,   31,   31,   31,   31,
       31,   31,   25,   31,   11,   13,   21,   31,    7,   14,
        3,   31,   31,   24,    8,    5,   31,   31,   17,   31,
       31,   31,   31,   31,   18,   22,   31,   31,   31,   31,
       31,   31,   12,   31,    2,    4,   31,   16,   31,    6,
       20,   31,   31,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       23,   24,   25,    1,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   22,   22,   36,   37,   38,
       39,   40,   22,   41,   42,   43,   44,   22,   45,   46,
       47,   48,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    2,    3,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[159] =
    {   0,
        0,    0,  180,  431,  431,  431,  431,  155,   46,  431,
      154,  431,  431,  431,  431,  431,  431,  431,  431,  141,
      431,  131,  130,  102,   30,  431,  431,   31,   32,   36,
       38,   42,   48,   53,   60,   67,   69,   71,   73,   78,
      431,   67,  431,  431,   60,  431,  112,  431,   93,  431,
      431,  431,   80,   92,   56,   82,   90,   98,  103,  104,
      105,  110,  111,  112,  116,  118,  122,  123,  129,  133,
      141,  140,  147,  146,  148,  156,  431,   56,   49,  161,
      162,  166,  167,  173,  172,  183,  187,  193,  197,  199,
      198,  203,  204,  205,  209,  217,  219,  221,  225,  227,

      431,  233,  237,  232,  241,  242,  243,  250,  254,  259,
      261,  265,  266,  267,  271,  273,  275,  281,  282,  286,
      287,  288,  292,  294,  298,  302,  303,  308,  309,  310,
      316,  315,  317,  323,  329,  330,  331,  336,  337,  341,
      343,  348,  352,  353,  357,  363,  365,  364,  371,  375,
      376,  377,  381,  382,  431,  425,  427,   58
    } ;

static const flex_int16_t yy_def[159] =
    {   0,
      155,    1,  155,  155,  155,  155,  155,  155,  156,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  157,  155,  155,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      155,  155,  155,  155,  156,  155,  156,  155,  155,  155,
      155,  155,  157,  155,  158,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  155,  155,  158,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,

      155,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,    0,  155,  155,  155
    } ;

static const flex_int16_t yy_nxt[483] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    4,   27,    4,   28,   29,   30,   31,
       32,   33,   25,   25,   34,   25,   35,   36,   25,   25,
       37,   38,   39,   25,   40,   25,   25,   25,   41,   42,
       43,   46,   54,   54,   54,   55,   55,   55,   54,   79,
       54,   55,   57,   55,   54,   46,   56,   55,   59,   47,
       54,   58,   78,   55,  155,   54,   60,   61,   55,   62,
      101,   55,   54,   47,   65,   55,   67,   63,   64,   54,
       66,   54,   55,   54,   55,   54,   55,   68,   55,   70,

       54,   71,   54,   55,   54,   55,   73,   55,   78,   49,
       69,   75,   54,   72,  155,   55,   77,   80,   76,   74,
       54,   52,   81,   55,   82,   54,   54,   54,   55,   55,
       55,   83,   54,   54,   54,   55,   55,   55,   54,   85,
       54,   55,   87,   55,   54,   54,   84,   55,   55,   51,
       50,   54,   88,   86,   55,   54,   90,   49,   55,   93,
       89,   48,   54,   54,   92,   55,   55,   91,   54,   54,
       54,   55,   55,   55,   44,   94,   95,   97,   54,  155,
       96,   55,   99,   54,   54,   98,   55,   55,   54,   54,
      100,   55,   55,  155,   54,   54,  103,   55,   55,  102,

      107,  108,  105,  106,  155,   54,  109,  104,   55,   54,
      155,  155,   55,  112,  110,   54,  111,  113,   55,   54,
       54,   54,   55,   55,   55,   54,   54,   54,   55,   55,
       55,   54,  155,  117,   55,  114,  115,  155,  116,   54,
      119,   54,   55,   54,   55,  155,   55,   54,  118,   54,
       55,  121,   55,  155,   54,   54,  120,   55,   55,   54,
      122,  124,   55,   54,   54,   54,   55,   55,   55,  123,
      155,  155,   54,  126,  125,   55,   54,  155,  127,   55,
      128,   54,  155,   54,   55,  129,   55,   54,   54,   54,
       55,   55,   55,   54,  131,   54,   55,   54,   55,  155,

       55,  133,  132,   54,   54,  130,   55,   55,   54,   54,
       54,   55,   55,   55,   54,  155,   54,   55,  135,   55,
       54,  134,  136,   55,   54,   54,  155,   55,   55,  137,
       54,   54,   54,   55,   55,   55,  138,   54,   54,   54,
       55,   55,   55,  142,  141,   54,  155,  155,   55,  139,
      140,   54,   54,   54,   55,   55,   55,  155,   54,   54,
      143,   55,   55,   54,  155,   54,   55,  146,   55,  155,
       54,  145,  144,   55,   54,   54,  147,   55,   55,   54,
      155,  155,   55,  149,  148,   54,   54,   54,   55,   55,
       55,  155,  155,   54,  150,  151,   55,   54,   54,   54,

       55,   55,   55,   54,   54,  152,   55,   55,  155,  155,
      155,  154,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  153,   45,   45,   45,   53,   53,
        3,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155
    } ;

static const flex_int16_t yy_chk[483] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   25,   28,   29,   25,   28,   29,   30,  158,
       31,   30,   29,   31,   32,   45,   28,   32,   31,    9,
       33,   30,   78,   33,   79,   34,   31,   32,   34,   32,
       78,   55,   35,   45,   34,   35,   35,   32,   33,   36,
       34,   37,   36,   38,   37,   39,   38,   36,   39,   37,

       40,   38,   53,   40,   56,   53,   39,   56,   54,   49,
       36,   40,   57,   38,   47,   57,   42,   56,   40,   39,
       58,   24,   57,   58,   58,   59,   60,   61,   59,   60,
       61,   59,   62,   63,   64,   62,   63,   64,   65,   62,
       66,   65,   64,   66,   67,   68,   61,   67,   68,   23,
       22,   69,   66,   63,   69,   70,   67,   20,   70,   70,
       66,   11,   72,   71,   69,   72,   71,   68,   74,   73,
       75,   74,   73,   75,    8,   70,   71,   73,   76,    3,
       72,   76,   75,   80,   81,   74,   80,   81,   82,   83,
       76,   82,   83,    0,   85,   84,   81,   85,   84,   80,

       85,   85,   83,   84,    0,   86,   85,   82,   86,   87,
        0,    0,   87,   86,   85,   88,   85,   87,   88,   89,
       91,   90,   89,   91,   90,   92,   93,   94,   92,   93,
       94,   95,    0,   93,   95,   88,   90,    0,   92,   96,
       95,   97,   96,   98,   97,    0,   98,   99,   94,  100,
       99,   98,  100,    0,  104,  102,   97,  104,  102,  103,
       99,  102,  103,  105,  106,  107,  105,  106,  107,  100,
        0,    0,  108,  104,  103,  108,  109,    0,  107,  109,
      108,  110,    0,  111,  110,  109,  111,  112,  113,  114,
      112,  113,  114,  115,  111,  116,  115,  117,  116,    0,

      117,  114,  112,  118,  119,  110,  118,  119,  120,  121,
      122,  120,  121,  122,  123,    0,  124,  123,  122,  124,
      125,  118,  123,  125,  126,  127,    0,  126,  127,  127,
      128,  129,  130,  128,  129,  130,  128,  132,  131,  133,
      132,  131,  133,  133,  132,  134,    0,    0,  134,  130,
      131,  135,  136,  137,  135,  136,  137,    0,  138,  139,
      134,  138,  139,  140,    0,  141,  140,  139,  141,    0,
      142,  138,  137,  142,  143,  144,  140,  143,  144,  145,
        0,    0,  145,  142,  141,  146,  148,  147,  146,  148,
      147,    0,    0,  149,  144,  147,  149,  150,  151,  152,

      150,  151,  152,  153,  154,  149,  153,  154,    0,    0,
        0,  153,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  152,  156,  156,  156,  157,  157,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "decl.l"
#line 2 "decl.l"
	#include <stdlib.h>
	#include <stdio.h>
	#include <string.h>
	#include "y.tab.h"
	#include "decl.h"
	#include "decl.c"
	int number;
	int flag =0;
	int flag1 = 0;
	int flag2 = 0;
	int flag3 = 0;
	int flag4 = 0;
	int f1 =0;int f2 =0;int f3 =0;int f4 = 0;int f5 = 0;int f6 =0;int f7 =0;int f8 =0;
	int f9 =0;int f10 =0;int f11 =0; int f12 =0;int f13 = 0;int f14 =0;int f15 =0; int f16 =0;int f17 = 0;
	int f18 = 0;int f19 = 0;int f20;int f21 = 0;
	int f22 = 0;
	int flag5 = 0;
	int flag6 = 0;
	int flag7 = 0;
	int flag8 = 0;
	struct Paramstruct *temp_param = NULL;
	struct TypeTable *temp_table = NULL;
	struct TypeTable *temp_table1 = NULL;
	struct Gsymbol *temp_one = NULL;
	struct GLsymbol *temp_one1 = NULL;
	struct ClassTable *temp_class = NULL;
	int rettype =0;

#line 627 "lex.yy.c"
#line 628 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 32 "decl.l"


#line 848 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 156 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 431 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "decl.l"
{if(f13 == 1 && f15 == 0){f14 = 1;}else if(flag3 == 0){f1 =1;}else{f5 = 1;}flag4 = 0;return DECL;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "decl.l"
{if(f13 == 1 && f15 == 0){f14 = 0; f15 = 1;}else if(flag3 == 0){f1 =0;}else{f5 = 0;}return ENDDECL;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "decl.l"
{flag5 = 1; return TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "decl.l"
{flag5 = 0; return ENDTYPE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "decl.l"
{f13 = 1; return CLASS;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "decl.l"
{f13 = 0; return ENDCLASS;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "decl.l"
{f17 = 1; return SELF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "decl.l"
{f7 = 1;f4 = 0;return BEG;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "decl.l"
{f7 = 0;return END;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "decl.l"
{f20 = 1;return NEW;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "decl.l"
{yylval.n2 = makeFuncNode("main", 1, NULL, 13);rettype = 1;return MAIN;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "decl.l"
{return RETURN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "decl.l"
{yylval.n2 = makeNullVar();return NUL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "decl.l"
{return THEN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "decl.l"
{return ELSE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "decl.l"
{f22 = 1; return EXTENDS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "decl.l"
{return ENDIF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "decl.l"
{return WHILE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "decl.l"
{return DO;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "decl.l"
{return ENDWHILE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "decl.l"
{return READ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "decl.l"
{return WRITE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "decl.l"
{return IF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "decl.l"
{return ALLOC;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "decl.l"
{return FREE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "decl.l"
{return INITIALIZE;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 60 "decl.l"
{char* name = yytext; yylval.n2 = makeLeafNodeStr(name, 11); return STRING;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "decl.l"
{	
										printf("ght\n");
										if(f14 == 1 && flag7 == 0){flag6 = 1;printf("ghts\n"); return INT;}
										else if(f14 == 1 && flag7 == 1){flag8 = 1;printf("ghts\n"); return INT;}
										else if(f13 == 1 && f16 == 0 && f15 == 0){flag4 = 1;printf("ghts\n"); return INT;}
										else if(f8 ==1){f9 =1; printf("ghts\n"); return INT;}
										else if(f2 ==1){f3 = 1; flag2 = 1; printf("ghts\n"); return INT;}
										else if(f1 == 0){flag3 = 1;flag4 = 1;if(f4 ==0){flag =1;flag4 = 1;} printf("ghts\n"); return INT;}
										else if(f2 == 0){flag =1;flag1 =1; printf("ghts\n"); return INT;}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "decl.l"
{	
										if(f14 == 1 && flag7 == 0){flag6 = 2; return STR;}
										else if(f14 == 1 && flag7 == 1){flag8 = 2; return STR;}
										else if(f13 == 1 && f16 == 0 && f15 == 0){flag4 = 2; return STR;}
										else if(f8 ==1){f9 =2;return STR;}
										else if(f2 ==1){f3 = 1; flag2 = 2; return STR;}
										else if(f1 == 0){flag3 = 1;flag4 = 2;if(f4 ==0){flag =1;flag4 = 2;}return STR;}
										else if(f2 == 0){flag =1;flag1 =2;return STR;}
									}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "decl.l"
{ 	if(f1 ==1){
											if(flag == 1){	
												char* name = yytext;
												char* name2 = strchr(name, '[');
												char* name3 = strchr(name, ']');
												char* name1 = malloc(sizeof(char*));
												char* num1 = malloc(sizeof(char*));
												int loc = (int)(name2 - name);
												int loc1 = (int)(name3 - name);
												strncpy(name1, name, loc);
												strncpy(num1, name+loc+1, loc1-1);
												int num = atoi(num1);
												struct Gsymbol* temp1 = Lookup(name1);
												if(temp1 == NULL){
													if(flag1 == 1){ 
														yylval.no = newVariableArr(name1, num, 1);
														return ID1;
													}
													else if(flag1 == 2){
														yylval.no = newVariableArr(name1, num, 2);
														return ID1;
													}
												}
												else{
													printf("Dec error7\n");
													exit(-1);
												}
											}
										}
										else if(f7 == 1){
												char* name = yytext;
												char* name2 = strchr(name, '[');
												char* name3 = strchr(name, ']');
												char* name1 = malloc(sizeof(char*));
												char* num1 = malloc(sizeof(char*));
												int loc = (int)(name2 - name);
												int loc1 = (int)(name3 - name);
												strncpy(name1, name, loc);
												strncpy(num1, name+loc+1, loc1-1);
												int num = atoi(num1);
												struct Lsymbol* temp1 = LookupLocal(name1);
												struct Gsymbol* temp2 = Lookup(name1);
												if(temp1 != NULL){
													yylval.n2 = makeArrayNode(name1, makeLeafNodeInt(num, 4), 12);
													return ID;
												}
												else if(temp2 != NULL){
													yylval.n2 = makeArrayNode(name1, makeLeafNodeInt(num, 4), 12);
													return ID;
												}
												else{
													printf("UnDec error6\n");
													exit(-1);
												}
										}
										else{
											if(flag == 1){	
												char* name = yytext;
												char* name2 = strchr(name, '[');
												char* name3 = strchr(name, ']');
												char* name1 = malloc(sizeof(char*));
												char* num1 = malloc(sizeof(char*));
												int loc = (int)(name2 - name);
												int loc1 = (int)(name3 - name);
												strncpy(name1, name, loc);
												strncpy(num1, name+loc+1, loc1-1);
												int num = atoi(num1);
												struct Lsymbol* temp1 = LookupLocal(name1);
												if(temp1 == NULL){
													if(flag4 == 1){
														flag4 = 0;
														yylval.n3 = newLVariableArr(name1, num, 1);
														return AID3;
													}
													else if(flag4 == 2){
														flag4 = 0;
														yylval.n3 = newLVariableArr(name1, num, 2);
														return AID3;
													}
												}
												else{
													printf("Dec error6\n");
													exit(-1);
												}
											}
										}
									}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 166 "decl.l"
{   char* name1 = yytext;
												printf("%s\n", name1);
										struct TypeTable *temp3 = TLookup(name1);
										if(temp3 != NULL){
											f11 = 1;
											yylval.n5 = temp3;
											if(f2 == 1){
												f3 = 1;
											}
											else if(f1 == 0){
												flag3 = 1;
											}
											temp_table1 = temp3;
											return ID4;
										}
										struct ClassTable *temp_cl = CLookup(name1);
										if(temp_cl != NULL){
											if(f13 == 1 && f14 == 1){
												f21 = 1;
												yylval.n7 = temp_cl;
												return ID6;

												break;
											}
										}
										if(f13 == 1 && f14 == 1){
											if(flag7 == 0){
												char* name1 = yytext;
												struct FieldList *temp1 = FLookup(name1);
												if(temp1 == NULL){
													if(flag6 == 1){
														struct TypeTable *temp2 = TLookup("int");
														yylval.n6 = newField(name1, temp2);
														flag6 = 0;
														return ID5;
													}
													else if(flag6 == 2){
														struct TypeTable *temp2 = TLookup("str");
														yylval.n6 = newField(name1, temp2);
														flag6 = 0;
														return ID5;
													}
													else if(f21 == 1 && f22 == 0){
														yylval.n6 = newField(name1, NULL);
														flag6 =0;
														return ID5;
													}
													else if(flag6 == 0){
														yylval.n6 = newField(name1, temp_table1);
														flag6 = 0;
														return ID5;
													}
												}
												else{
													printf("Dec error11\n");
													exit(-1);
												}
											}
											else{
												char* name1 = yytext;
												struct Paramstruct* param = LookupParam(name1, head1);
												if(param == NULL){
													if(flag8 == 1){ 
													yylval.n1 = newParam(name1, 1);
													flag8 =0;
													return PARAM;
													}
													else if(flag8 == 2){
														yylval.n1 = newParam(name1, 2);
														flag8 =0;
														return PARAM;
													}
													else if(f11 == 1){
														yylval.n1 = newParam(name1, 3);
														return PARAM;
														f11 = 0;
													}
												}
												else{
													printf("dec error12\n");
													exit(-1);
												}
											}
										}
										else if(f13 == 1 && f15 == 1 && f16 == 0){
											char* name1 = yytext;
											struct MemberFuncList *temp = MLookup(name1);
											if(temp != NULL){
												if(temp->paramlist != NULL){
													temp_param = temp->paramlist;
													f18 = 1;
												}
												f16 = 1;
												if(flag4 == 1){
													flag4 =0;
													yylval.n2 = makeFuncNodeC(name1, temp_class, 1, 13);
													rettype = 1;
													return ID;
												}
												else if(flag4 == 2){
													flag4 =0;
													yylval.n2 = makeFuncNodeC(name1, temp_class, 2, 13);
													rettype = 2;
													return ID;
												}
												else if(f11 == 1){
													yylval.n2 = makeFuncNodeC(name1, temp_class, 3, 13);
													rettype = 3;
													return ID;
												}
											}
											else{
												printf("Dec error14\n");
												exit(-1);
											}
										}
										else if(flag5 == 1 && f8 == 0){
											char* name1 = yytext;
											struct TypeTable *temp = TLookup(name1);
											if(temp == NULL){
												yylval.n5 = newUserType(name1);
												f11 =0;
												return ID4;
											}
											else{
												printf("Dec error8\n");
												exit(-1);
											}
										}
										else if(flag5 == 1 && f8 == 1){
											char* name1 = yytext;
											if(f9 == 1){
												struct FieldList *temp1 = FLookup(name1);
												if(temp1 == NULL){
													struct TypeTable *temp2 = TLookup("int");
													yylval.n6 = newField(name1, temp2);
													return ID5;
												}
												else{
													printf("Dec error9\n");
													exit(-1);
												}
											}
											else if(f9 == 2){
												struct FieldList *temp1 = FLookup(name1);
												if(temp1 == NULL){
													struct TypeTable *temp2 = TLookup("str");
													yylval.n6 = newField(name1, temp2);
													return ID5;
												}
												else{
													printf("Dec error9\n");
													exit(-1);
												}
											}
											else{
												struct FieldList *temp = FLookup(name1);
												if(temp == NULL){
													yylval.n6 = newField(name1, temp_table1);
													return ID5;
												}
												else{
													printf("Dec error9\n");
													exit(-1);
												}
											}											
										}
										else if(f3 == 1){
											char* name1 = yytext;
											struct Paramstruct* param = LookupParam(name1, head1);
											if(param == NULL){
												if(flag2 == 1){ 
													yylval.n1 = newParam(name1, 1);
													flag2 =0;
													return PARAM;
												}
												else if(flag2 == 2){
													yylval.n1 = newParam(name1, 2);
													flag2 =0;
													return PARAM;
												}
												else if(f11 == 1){
													yylval.n1 = newParam(name1, 3);
													return PARAM;
												}
											f3 =0;
											}
										}
										else if(f5 == 1){
											char* name1 = yytext;
											struct Lsymbol *temp = LookupLocal(name1);
											if(temp == NULL){
												if(flag4 == 1)
												{
													yylval.n3 = newLVariable(name1,NULL, 1);
													return ID3;
												}
												else if(flag4 == 2)
												{
													yylval.n3 = newLVariable(name1,NULL, 2);
													return ID3;
												}
												else if(f11 == 1)
												{
													yylval.n3 = newLVariable(name1,temp_table1, 3);
													return ID3;
												}
											}
											else{
												printf("Dec error5\n");
												exit(-1);
											}
										}
										else if(f4 == 1){
											char* name1 = yytext;
											struct Paramstruct* param = LookupParam(name1, temp_param);
											if(param == NULL && f18 == 1){
												printf("error\n");
												f18 = 0;
												exit(-1);
											}
											else{
												struct Lsymbol *temp = LookupLocal(name1);
												if(temp == NULL){
													if(flag4 == 1){ 
														newLVariableG(name1, NULL, 1);
														yylval.n1 = param;
														flag4 =0;
														return PARAM;
													}
													else if(flag4 == 2){
														newLVariableG(name1, NULL, 2);
														yylval.n1 = param;
														flag4 = 0;
														return PARAM;	
													}
													else if(f11 == 1)
													{
														newLVariableG(name1, param->typet, 3);
														yylval.n1 = param;
														f11 = 0;
														return PARAM;
													}
												}
												else{
													printf("Dec error4\n");
													exit(-1);
												}
											}
										}
										else if(f7 == 1 && f20 == 0){
											char* name1 = yytext;
											printf("%s..vnvn\n", name1);
											struct Lsymbol* temp2;
											struct Gsymbol* temp1;
											if(f12 == 0){
												temp2 = LookupLocal(name1);
												if(temp2 != NULL){
													if(temp2->type == 3){
														struct TypeTable *temp = temp2->typet;
														yylval.n2 = makeLeafNodeVarL(name1, temp2,temp,3, 19);
														temp_table = temp;
														return ID;
													}
													else if(temp2->type == 1){
														yylval.n2 = makeLeafNodeVarL(name1, temp2,NULL,1, 5);
														return ID;
													}
													else if(temp2->type == 2){
														yylval.n2 = makeLeafNodeVarL(name1, temp2,NULL,2, 5);
														return ID;
													}
												}
												temp1 = Lookup(name1);
												if(temp1 != NULL){
													if(temp1->type  == 3){
														struct TypeTable *temp = temp1->typet;
														temp_table = temp;
														yylval.n2 = makeLeafNodeVarG(name1, temp1,temp,3, 19);
														return ID;
													}
													else if(temp1->type == 1){
														yylval.n2 = makeLeafNodeVarG(name1, temp1,NULL,1, 5);
														return ID;
													}
													else if(temp1->type == 2){
														yylval.n2 = makeLeafNodeVarG(name1, temp1,NULL,2, 5);
														return ID;
													}
													else if(temp1->type == 4){
														temp_class = temp1->Ctype;
														yylval.n2 = makeLeafNodeVarG(name1, temp1,NULL,4, 5);
														return ID;	
													}
												}
												else{
													printf("Dec error3\n");
													exit(-1);
												}
											}
											else if(f17 == 1){
												f17 = 0;
												f12 = 0;
												printf("yujh\n");
												struct FieldList *temp = FLookup(name1);
												struct MemberFuncList *temp1 = MLookup(name1);
												printf("tnv\n");
												if(temp != NULL){
													printf("tug\n");
													if(temp->typet != NULL){
														if(temp->typet->index == 1){
															yylval.n2 = makeLeafNodeVarC(name1, temp_class,temp->typet, 1, 23);
															return ID;
														}
														else if(temp->typet->index == 2){
															yylval.n2 = makeLeafNodeVarC(name1, temp_class,temp->typet, 2, 23);
															return ID;
														}
														else{
															yylval.n2 = makeLeafNodeVarC(name1, temp_class,temp->typet, 3, 23);
															return ID;
														}
													}
													else{
														yylval.n2 = makeLeafNodeVarC(name1, temp_class, NULL, 4, 23);
														return ID;
													}
												}
												else if(temp1 != NULL){
													printf("yot\n");
													if(temp1->typet->index == 1){
														yylval.n2 = makeLeafNodeVarC(name1, temp_class,temp1->typet, 1, 23);
														return ID;
													}
													else if(temp1->typet->index == 2){
														yylval.n2 = makeLeafNodeVarC(name1, temp_class,temp1->typet, 2, 23);
														return ID;
													}
													else{
														yylval.n2 = makeLeafNodeVarC(name1, temp_class,temp1->typet, 3, 23);
														return ID;
													}	
												}
												else{
													printf("Dec error15\n");
													exit(-1);
												}
											}
											else{
												struct FieldList *temp4 = LookupField(name1, temp_class->Memberfield);
												struct MemberFuncList *temp5 = LookupMemFunc(name1, temp_class->Vfuncptr);
												struct FieldList* temp3;
												if(temp_table != NULL){
													temp3 = LookupF(temp_table, name1);
												}
												f12 =0;
												if(temp4 != NULL){
													yylval.n2 = makeLeafNodeVarC(temp4->name, temp_class, temp4->typet, 0, 23);
													return ID;
												}
												else if(temp5 != NULL){
													yylval.n2 = makeLeafNodeVarC(temp5->name, temp_class,  temp5->typet, 0, 23);
													return ID;
												}
												else if(temp3 != NULL){
													struct TypeTable *temp = temp3->typet;
													temp_table = temp;
													if(temp2 != NULL){
														if(temp->name == "int"){
															yylval.n2 = makeLeafNodeVarL(name1, temp2,temp,1, 20);
															return ID;
														}
														else if(temp->name == "str"){
															yylval.n2 = makeLeafNodeVarL(name1, temp2,temp,2, 20);
															return ID;
														}
														else{
															yylval.n2 = makeLeafNodeVarL(name1, temp2,temp,3, 20);
															return ID;
														}
													}
													else{
														if(temp->name == "int"){
															yylval.n2 = makeLeafNodeVarG(name1, temp1,temp,1, 20);
															return ID;
														}
														else if(temp->name == "str"){
															yylval.n2 = makeLeafNodeVarG(name1, temp1,temp,2, 20);
															return ID;
														}
														else{
															yylval.n2 = makeLeafNodeVarG(name1, temp1,temp,3, 20);
															return ID;
														}
													}
												}
												else{
													printf("Dec error31\n");
													exit(-1);
												}
											}
										}
										if(f13 == 1 && f20 == 0){
											char* name1 = yytext;
											struct ClassTable *temp = CLookup(name1);
											if(temp == NULL){
												yylval.n7 = newClass(name1);
												temp_class = CLookup(name1);
												return ID6;
											}
											else if(temp != NULL && f22 == 1){
												yylval.n7 = CLookup(name1);
												return ID6;
											}
											else{
												printf("dec error10\n");
												exit(-1);
											}
										}
										else if(f3 ==0){
											if(flag3 == 1 && f20 == 0){
												char* name1 = yytext;
												struct Gsymbol* temp1 = Lookup(name1);
												if(temp1 != NULL){
													rettype = temp1->type;
													temp_param = temp1->paramlist;
													f18 = 1;
													if(flag4 == 1){
														flag4 = 0;
														yylval.n2 = makeFuncNode(name1,1,temp1, 13);
														return ID;
													}
													else if(flag4 == 2){
														flag4 = 0;
														yylval.n2 = makeFuncNode(name1,2,temp1, 13);
														return ID;
													}
													else if(f11 == 1){
														yylval.n2 = makeFuncNode(name1,3,temp1, 13);
														return ID;
													}
												}
												else{
													printf("Dec error2\n");
													exit(-1);
												}
											}
											else{	
												char* name1 = yytext;
												struct Gsymbol* temp1 = Lookup(name1);
												struct ClassTable *temp2 = CLookup(name1);
												if(temp2 != NULL){
													yylval.n7 = temp2;
													temp_class = temp2;
													f19 = 1;
													f20 = 0;
													return ID6;

												}
												if(temp1 == NULL){

													if(flag1 == 1)
													{ 
														yylval.no = newVariable(name1,NULL, 1);
														return ID1;
													}
													else if(flag1 == 2)
													{
														yylval.no = newVariable(name1,NULL, 2);
														return ID1;
													}
													else if(f19 == 1){
														yylval.no = newVariableC(name1, temp_class, 4);
														return ID1;
													}
													else if(f11 == 1)
													{
														yylval.no = newVariable(name1,temp_table1, 3);
														return ID1;
													}
												}
												else{
													printf("Dec error1\n");
													exit(-1);
												}
											}
										}
									}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 654 "decl.l"
{if(f1 == 0){return *yytext;}}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 655 "decl.l"
{if(f1 == 0){return *yytext;}}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 656 "decl.l"
{if(f13 == 1 && f15 == 0){flag7 = 1;}else if(f13 == 1 && f15 == 1 && f16 == 0){f4 =1;}else if(flag3 ==0){f2 = 1;}else if(f5 == 0 && f7 ==0){f4 = 1;}printf("dj\n");return *yytext;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 657 "decl.l"
{printf("gty\n");if(f13 == 1 && f15 == 0){flag7 = 0;}else if(f13 == 1 && f15 == 1 && f16 == 0){f4 =0;}else if(flag3 ==0){f2 = 0;f3 =0;}else if(f5 == 0 && f7 ==0){f4 = 0;}printf("hetj\n");makeNull();return *yytext;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 658 "decl.l"
{flag1 = 0; flag = 0;f3= 0; f2 = 0; f11 =0;f9=0;flag4 =0;f19 = 0;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 659 "decl.l"
{return *yytext;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 660 "decl.l"
{}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 661 "decl.l"
{}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 662 "decl.l"
{}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 663 "decl.l"
{return PLUS;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 664 "decl.l"
{return MINUS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 665 "decl.l"
{return MUL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 666 "decl.l"
{return MOD;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 667 "decl.l"
{return DIV;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 668 "decl.l"
{return EQT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 669 "decl.l"
{return GT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 670 "decl.l"
{return LT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 671 "decl.l"
{return EQ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 672 "decl.l"
{return NE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 673 "decl.l"
{return GE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 674 "decl.l"
{return LE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 675 "decl.l"
{return OR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 676 "decl.l"
{return AND;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 677 "decl.l"
{number = atoi(yytext); yylval.n2 = makeLeafNodeInt(number, 4); return ID;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 678 "decl.l"
{if(f13 == 1 && f15 == 1){f16 = 1;}if(flag5 == 1){f8 = 1;}return *yytext;flag4 = 0;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 679 "decl.l"
{if(f13 == 1 && f15 == 1){f16 = 0;}if(flag5 == 1){f8 = 0;}flag3 = 0;return *yytext;flag4 = 0;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 680 "decl.l"
{f12 =1;return *yytext;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 681 "decl.l"
{yyerror("unknown character\n");exit(1);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 684 "decl.l"
ECHO;
	YY_BREAK
#line 1796 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 156 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 156 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 155);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 684 "decl.l"



int yywrap(void){
    return 1;
}
